INSERT INTO encuestadores (nombre) VALUES ('Juan');
INSERT INTO encuestadores (nombre) VALUES ('Pedro');
INSERT INTO encuestadores (nombre) VALUES ('Maria');
INSERT INTO encuestadores (nombre) VALUES ('Jose');
INSERT INTO encuestadores (nombre) VALUES ('Pablo');
INSERT INTO encuestadores (nombre) VALUES ('Lucia');
INSERT INTO encuestadores (nombre) VALUES ('Marta');

INSERT INTO equipos (nombre) VALUES ('Talleres');
INSERT INTO equipos (nombre) VALUES ('Belgrano');
INSERT INTO equipos (nombre) VALUES ('Instituto');
INSERT INTO equipos (nombre) VALUES ('Racing');
INSERT INTO equipos (nombre) VALUES ('Las Palmas');
INSERT INTO equipos (nombre) VALUES ('Otros');


INSERT INTO barrios (nombre) VALUES ('Alta Cordoba');
INSERT INTO barrios (nombre) VALUES ('Alberdi');
INSERT INTO barrios (nombre) VALUES ('Centro');
INSERT INTO barrios (nombre) VALUES ('Nueva Cordoba');
INSERT INTO barrios (nombre) VALUES ('General Paz');
INSERT INTO barrios (nombre) VALUES ('Marques');
INSERT INTO barrios (nombre) VALUES ('Jardin');


INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 1, 1, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 1, 2, 120);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 1, 3, 97);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 1, 4, 56);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 1, 5, 12);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 1, 6, 2);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 2, 1, 87);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 2, 2, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 2, 3, 120);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 2, 4, 97);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 2, 5, 56);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 2, 6, 12);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 3, 1, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 3, 2, 87);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 3, 3, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 3, 4, 120);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 3, 5, 97);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 3, 6, 56);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 4, 1, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 4, 2, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 4, 3, 87);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 4, 4, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 4, 5, 120);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 4, 6, 97);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 5, 1, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 5, 2, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 5, 3, 100);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 5, 4, 56);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 5, 5, 100);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 5, 6, 100);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 6, 1, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 6, 2, 156);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 6, 3, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 6, 4, 87);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 6, 5, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 6, 6, 120);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 7, 1, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 7, 2, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 7, 3, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 7, 4, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (1, 7, 5, 134);

INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 1, 1, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 1, 2, 120);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 1, 3, 97);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 1, 4, 56);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 1, 5, 12);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 1, 6, 2);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 2, 1, 87);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 2, 2, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 2, 3, 120);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 2, 4, 97);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 2, 5, 56);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 2, 6, 12);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 3, 1, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 3, 2, 87);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 3, 3, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 3, 4, 120);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 3, 5, 97);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 3, 6, 56);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 4, 1, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 4, 2, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 4, 3, 87);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 4, 4, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 4, 5, 120);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 4, 6, 97);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 5, 1, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 5, 2, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 5, 3, 100);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 5, 4, 56);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 5, 5, 100);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 5, 6, 100);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 6, 1, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 6, 2, 156);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 6, 3, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 6, 4, 87);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 6, 5, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 6, 6, 120);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 7, 1, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 7, 2, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 7, 3, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 7, 4, 134);
INSERT INTO resultados (encuestador_id, barrio_id, equipo_id, votos) VALUES (2, 7, 5, 134);
